import type { ThemeTokenMap } from "./themeTokens";

export type ThemeVariant = "light" | "dark";

export interface ThemeDefinition {
    name: string;
    variant: ThemeVariant;
    tokens: ThemeTokenMap;
    source: "builtin" | "user";
}

const NEUTRAL_PALETTE: ThemeTokenMap = {
    "neutral.50": "#f9fafb",
    "neutral.100": "#f3f4f6",
    "neutral.200": "#e5e7eb",
    "neutral.300": "#d1d5db",
    "neutral.400": "#9ca3af",
    "neutral.500": "#6b7280",
    "neutral.600": "#4b5563",
    "neutral.700": "#374151",
    "neutral.800": "#1f2937",
    "neutral.900": "#111827",
};

const BLUE_PALETTE: ThemeTokenMap = {
    "accent.50": "#eff6ff",
    "accent.100": "#dbeafe",
    "accent.200": "#bfdbfe",
    "accent.300": "#93c5fd",
    "accent.400": "#60a5fa",
    "accent.500": "#3b82f6",
    "accent.600": "#2563eb",
    "accent.700": "#1d4ed8",
    "accent.800": "#1e40af",
    "accent.900": "#1e3a8a",
};

const BASE_LIGHT_TOKENS: ThemeTokenMap = {
    ...NEUTRAL_PALETTE,
    ...BLUE_PALETTE,
    "accent.default": "#2563eb",
    "accent.swatch1": "#3d14b8",
    "accent.swatch2": "#0ea5e9",
    "accent.swatch3": "#10b981",
    "accent.swatch4": "#f59e0b",
    "accent.swatch5": "#ef4444",
    "accent.swatch6": "#8b5cf6",
    "accent.accent2": "#5468e0",
    "accent.soft": "rgba(52,82,214,.12)",
    "semantic.amber": "#b4762a",
    "semantic.amberSoft": "rgba(180,118,42,.13)",
    "semantic.green": "#3f8f57",
    "semantic.pink": "#b0468a",
    "semantic.pinkSoft": "rgba(176,70,138,.12)",
    "background.app": "#f2f0ea",
    "background.primary": "#ffffff",
    "background.secondary": "#f9fafb",
    "background.tertiary": "#f3f4f6",
    "background.elevated": "#ffffff",
    "background.hover": "rgba(32,28,22,.055)",
    "background.active": "rgba(52,82,214,.10)",
    "text.primary": "#111827",
    "text.secondary": "#1f2937",
    "text.tertiary": "#374151",
    "text.muted": "#6b7280",
    "text.link": "#2563eb",
    "border.light": "#e5e7eb",
    "border.medium": "#d1d5db",
    "border.dark": "#9ca3af",

    "semantic.primary": "var(--color-blue-600)",
    "semantic.primaryForeground": "#ffffff",
    "semantic.secondary": "var(--color-bg-tertiary)",
    "semantic.secondaryForeground": "var(--color-text-primary)",
    "semantic.muted": "var(--color-bg-tertiary)",
    "semantic.mutedForeground": "var(--color-text-muted)",
    "semantic.accent": "var(--color-bg-tertiary)",
    "semantic.accentForeground": "var(--color-text-primary)",
    "semantic.destructive": "#dc2626",
    "semantic.destructiveForeground": "#ffffff",
    "semantic.border": "var(--color-border-light)",
    "semantic.input": "var(--color-border-light)",
    "semantic.ring": "var(--color-blue-600)",

    "sidebar.background": "var(--color-bg-primary)",
    "sidebar.foreground": "var(--color-text-primary)",
    "sidebar.primary": "var(--color-blue-600)",
    "sidebar.primaryForeground": "#ffffff",
    "sidebar.accent": "var(--color-bg-tertiary)",
    "sidebar.accentForeground": "var(--color-text-primary)",
    "sidebar.border": "var(--color-border-light)",
    "sidebar.ring": "var(--color-blue-600)",

    "graph.background": "var(--color-bg-secondary)",
    "graph.node": "var(--color-blue-500)",
    "graph.nodeOrphan": "var(--color-gray-400)",
    "graph.nodeMissing": "var(--color-gray-300)",
    "graph.nodeLabel": "var(--color-text-primary)",
    "graph.edge": "var(--color-border-medium)",
    "graph.edgeBroken": "var(--color-gray-400)",
    "graph.nodeActive": "var(--color-blue-600)",

    "code.string": "#16a34a",
    "code.function": "#2563eb",
    "code.inline": "var(--color-text-primary)",
    "code.inlineBg": "color-mix(in srgb, var(--color-bg-tertiary) 85%, transparent)",
    "code.inlineBorder": "color-mix(in srgb, var(--color-border-medium) 70%, transparent)",
    "code.hashtag": "#7c3aed",
    "code.hashtagBg": "rgba(124, 58, 237, 0.1)",

    "panel.background": "var(--color-bg-primary)",
    "panel.border": "var(--color-border-light)",
    "panel.header": "color-mix(in srgb, var(--color-bg-primary) 70%, var(--color-bg-secondary))",
    "panel.footer": "color-mix(in srgb, var(--color-bg-primary) 70%, var(--color-bg-secondary))",
    "panel.hover": "color-mix(in srgb, var(--color-bg-primary) 85%, var(--color-bg-tertiary))",
    "panel.active": "var(--color-bg-tertiary)",
    "overlay.scrim": "color-mix(in srgb, var(--color-text-primary) 20%, transparent)",
    "highlight.background": "color-mix(in srgb, var(--color-blue-400) 25%, transparent)",
    "highlight.text": "var(--color-blue-700)",
    "kbd.background": "var(--color-bg-tertiary)",
    "kbd.border": "var(--color-border-light)",
    "kbd.text": "var(--color-text-secondary)",
    "alert.background": "color-mix(in srgb, var(--destructive) 12%, transparent)",
    "alert.border": "var(--destructive)",
    "alert.text": "var(--destructive)",
    "callout.default": "var(--primary)",
    "callout.info": "#448aff",
    "callout.tip": "#00bfa5",
    "callout.warning": "#ff9100",
    "callout.danger": "#ff1744",
    "callout.success": "#00c853",
    "callout.example": "#7c4dff",
    "callout.quote": "#9e9e9e",
    "callout.terminal": "#24292e",
};

const BASE_DARK_TOKENS: ThemeTokenMap = {
    ...NEUTRAL_PALETTE,
    ...BLUE_PALETTE,
    "accent.default": "#3b82f6",
    "accent.swatch1": "#3d14b8",
    "accent.swatch2": "#0ea5e9",
    "accent.swatch3": "#10b981",
    "accent.swatch4": "#f59e0b",
    "accent.swatch5": "#ef4444",
    "accent.swatch6": "#8b5cf6",
    "accent.accent2": "#95a2f4",
    "accent.soft": "rgba(124,140,240,.15)",
    "semantic.amber": "#d9a05a",
    "semantic.amberSoft": "rgba(217,160,90,.15)",
    "semantic.green": "#5cb377",
    "semantic.pink": "#d97fbb",
    "semantic.pinkSoft": "rgba(217,127,187,.15)",
    "background.app": "#141310",
    "background.elevated": "#211f1b",
    "background.hover": "rgba(255,255,255,.055)",
    "background.active": "rgba(124,140,240,.16)",
    "background.primary": "#0f0f0f",
    "background.secondary": "#1a1a1a",
    "background.tertiary": "#262626",
    "text.primary": "#fafafa",
    "text.secondary": "#e5e5e5",
    "text.tertiary": "#a3a3a3",
    "text.muted": "#737373",
    "text.link": "#3b82f6",
    "border.light": "#262626",
    "border.medium": "#404040",
    "border.dark": "#525252",

    "semantic.primary": "var(--color-blue-500)",
    "semantic.primaryForeground": "#ffffff",
    "semantic.secondary": "var(--color-bg-tertiary)",
    "semantic.secondaryForeground": "var(--color-text-primary)",
    "semantic.muted": "var(--color-bg-tertiary)",
    "semantic.mutedForeground": "var(--color-text-muted)",
    "semantic.accent": "var(--color-bg-tertiary)",
    "semantic.accentForeground": "var(--color-text-primary)",
    "semantic.destructive": "#ef4444",
    "semantic.destructiveForeground": "#ffffff",
    "semantic.border": "var(--color-border-light)",
    "semantic.input": "var(--color-border-medium)",
    "semantic.ring": "var(--color-blue-500)",

    "sidebar.background": "var(--color-bg-secondary)",
    "sidebar.foreground": "var(--color-text-primary)",
    "sidebar.primary": "var(--color-blue-500)",
    "sidebar.primaryForeground": "#ffffff",
    "sidebar.accent": "var(--color-bg-tertiary)",
    "sidebar.accentForeground": "var(--color-text-primary)",
    "sidebar.border": "var(--color-border-light)",
    "sidebar.ring": "var(--color-blue-500)",

    "graph.background": "var(--color-bg-secondary)",
    "graph.node": "var(--color-blue-400)",
    "graph.nodeOrphan": "var(--color-gray-500)",
    "graph.nodeMissing": "var(--color-gray-600)",
    "graph.nodeLabel": "var(--color-text-primary)",
    "graph.edge": "var(--color-border-medium)",
    "graph.edgeBroken": "var(--color-gray-600)",
    "graph.nodeActive": "var(--color-blue-500)",

    "code.string": "#16a34a",
    "code.function": "#60a5fa",
    "code.inline": "var(--color-text-primary)",
    "code.inlineBg": "color-mix(in srgb, var(--color-bg-tertiary) 92%, transparent)",
    "code.inlineBorder": "color-mix(in srgb, var(--color-border-medium) 80%, transparent)",
    "code.hashtag": "#8b5cf6",
    "code.hashtagBg": "rgba(139, 92, 246, 0.15)",

    "panel.background": "var(--color-bg-secondary)",
    "panel.border": "var(--color-border-light)",
    "panel.header": "color-mix(in srgb, var(--color-bg-secondary) 70%, var(--color-bg-tertiary))",
    "panel.footer": "color-mix(in srgb, var(--color-bg-secondary) 70%, var(--color-bg-tertiary))",
    "panel.hover": "color-mix(in srgb, var(--color-bg-secondary) 75%, var(--color-bg-tertiary))",
    "panel.active": "var(--color-bg-tertiary)",
    "overlay.scrim": "color-mix(in srgb, var(--color-text-primary) 30%, transparent)",
    "highlight.background": "color-mix(in srgb, var(--color-blue-400) 25%, transparent)",
    "highlight.text": "var(--color-blue-300)",
    "kbd.background": "var(--color-bg-tertiary)",
    "kbd.border": "var(--color-border-medium)",
    "kbd.text": "var(--color-text-secondary)",
    "alert.background": "color-mix(in srgb, var(--destructive) 18%, transparent)",
    "alert.border": "var(--destructive)",
    "alert.text": "var(--destructive)",
    "callout.default": "var(--primary)",
    "callout.info": "#82aaff",
    "callout.tip": "#00c2a8",
    "callout.warning": "#ffb454",
    "callout.danger": "#ff7b72",
    "callout.success": "#2bd86f",
    "callout.example": "#b39dfb",
    "callout.quote": "#b0b0b0",
    "callout.terminal": "#0d1117",
};

function createTheme(name: string, variant: ThemeVariant, overrides: ThemeTokenMap): ThemeDefinition {
    const base = variant === "dark" ? BASE_DARK_TOKENS : BASE_LIGHT_TOKENS;
    return {
        name,
        variant,
        tokens: { ...base, ...overrides },
        source: "builtin",
    };
}

export const BUILTIN_THEMES: ThemeDefinition[] = [
    createTheme("Catppuccin Latte", "light", {
        "background.primary": "#eff1f5",
        "background.secondary": "#e6e9ef",
        "background.tertiary": "#dce0e8",
        "text.primary": "#4c4f69",
        "text.secondary": "#5c5f77",
        "text.tertiary": "#6c6f85",
        "text.muted": "#8c8fa1",
        "border.light": "#ccd0da",
        "border.medium": "#bcc0cc",
        "border.dark": "#9ca0b0",
        "accent.default": "#94e2d5",
        "code.string": "#40a02b",
        "code.function": "#7287fd",
        "code.hashtag": "#8839ef",
        "code.hashtagBg": "rgba(136, 57, 239, 0.12)",
    }),
    createTheme("Catppuccin Mocha", "dark", {
        "background.primary": "#1e1e2e",
        "background.secondary": "#181825",
        "background.tertiary": "#11111b",
        "text.primary": "#cdd6f4",
        "text.secondary": "#bac2de",
        "text.tertiary": "#a6adc8",
        "text.muted": "#7f849c",
        "border.light": "#313244",
        "border.medium": "#45475a",
        "border.dark": "#585b70",
        "accent.default": "#94e2d5",
        "code.string": "#a6e3a1",
        "code.function": "#89b4fa",
        "code.hashtag": "#cba6f7",
        "code.hashtagBg": "rgba(203, 166, 247, 0.16)",
    }),
    createTheme("Warm Paper", "light", {
        "background.app": "#f2f0ea",
        "background.primary": "#fdfcf9",
        "background.secondary": "#f7f5f0",
        "background.tertiary": "#f2f0ea",
        "background.elevated": "#ffffff",
        "background.hover": "rgba(32,28,22,.055)",
        "background.active": "rgba(52,82,214,.10)",
        "text.primary": "#211d18",
        "text.secondary": "#55504a",
        "text.tertiary": "#8c847b",
        "text.muted": "#aaa298",
        "border.light": "#e7e2d9",
        "border.medium": "#dcd6cb",
        "border.dark": "#c9c3b8",
        "accent.default": "#3452d6",
        "accent.accent2": "#5468e0",
        "accent.soft": "rgba(52,82,214,.12)",
        "semantic.amber": "#b4762a",
        "semantic.amberSoft": "rgba(180,118,42,.13)",
        "semantic.green": "#3f8f57",
        "semantic.pink": "#b0468a",
        "semantic.pinkSoft": "rgba(176,70,138,.12)",
        "text.link": "#3452d6",
        "code.string": "#3f8f57",
        "code.function": "#3452d6",
        "code.hashtag": "#b4762a",
        "code.hashtagBg": "rgba(180,118,42,.12)",
    }),
    createTheme("Warm Paper Dark", "dark", {
        "background.app": "#141310",
        "background.primary": "#100f0d",
        "background.secondary": "#1a1916",
        "background.tertiary": "#141310",
        "background.elevated": "#211f1b",
        "background.hover": "rgba(255,255,255,.055)",
        "background.active": "rgba(124,140,240,.16)",
        "text.primary": "#ece8e1",
        "text.secondary": "#a8a29a",
        "text.tertiary": "#726c63",
        "text.muted": "#565048",
        "border.light": "#2a2823",
        "border.medium": "#38352e",
        "border.dark": "#4a463c",
        "accent.default": "#7c8cf0",
        "accent.accent2": "#95a2f4",
        "accent.soft": "rgba(124,140,240,.15)",
        "semantic.amber": "#d9a05a",
        "semantic.amberSoft": "rgba(217,160,90,.15)",
        "semantic.green": "#5cb377",
        "semantic.pink": "#d97fbb",
        "semantic.pinkSoft": "rgba(217,127,187,.15)",
        "text.link": "#7c8cf0",
        "code.string": "#5cb377",
        "code.function": "#7c8cf0",
        "code.hashtag": "#d9a05a",
        "code.hashtagBg": "rgba(217,160,90,.15)",
    }),
    createTheme("Default", "light", {
        "background.primary": "#f3f4f6",
        "background.secondary": "#eceff2",
        "background.tertiary": "#e2e6ea",
        "text.primary": "#1f2933",
        "text.secondary": "#2f3a43",
        "text.tertiary": "#3f4a53",
        "text.muted": "#66717a",
        "border.light": "#d3d8de",
        "border.medium": "#c2c9d1",
        "border.dark": "#aab3bd",
        "accent.default": "#5f7cc2",
        "code.string": "#2f855a",
        "code.function": "#2563eb",
        "code.hashtag": "#7c3aed",
        "code.hashtagBg": "rgba(124, 58, 237, 0.1)",
    }),
    createTheme("Default Dark", "dark", {
        "background.primary": "#141618",
        "background.secondary": "#1b1f23",
        "background.tertiary": "#252a30",
        "text.primary": "#e7e7e7",
        "text.secondary": "#c9c9c9",
        "text.tertiary": "#9aa0a6",
        "text.muted": "#7a7f86",
        "border.light": "#2f343a",
        "border.medium": "#3b4148",
        "border.dark": "#4a5159",
        "accent.default": "#5f7cc2",
        "code.string": "#addb67",
        "code.function": "#82aaff",
        "code.hashtag": "#c792ea",
        "code.hashtagBg": "rgba(199, 146, 234, 0.1)",
    }),
    createTheme("Ocean", "light", {
        "background.primary": "#f3f7fb",
        "background.secondary": "#e8f0f8",
        "background.tertiary": "#dbe7f4",
        "text.primary": "#0f172a",
        "text.secondary": "#1e293b",
        "text.tertiary": "#334155",
        "text.muted": "#64748b",
        "border.light": "#d7e3f1",
        "border.medium": "#c2d4ea",
        "border.dark": "#a8c1dd",
        "accent.default": "#2563eb",
        "code.string": "#16a34a",
        "code.function": "#2563eb",
        "code.hashtag": "#7c3aed",
        "code.hashtagBg": "rgba(124, 58, 237, 0.1)",
    }),
    createTheme("Ocean Dark", "dark", {
        "background.primary": "#0f172a",
        "background.secondary": "#141c30",
        "background.tertiary": "#1b263d",
        "text.primary": "#e2e8f0",
        "text.secondary": "#cbd5f5",
        "text.tertiary": "#94a3b8",
        "text.muted": "#7c8aa5",
        "border.light": "#1f2a44",
        "border.medium": "#2b3a5d",
        "border.dark": "#3a4b73",
        "accent.default": "#60a5fa",
        "code.string": "#34d399",
        "code.function": "#60a5fa",
        "code.hashtag": "#a78bfa",
        "code.hashtagBg": "rgba(167, 139, 250, 0.15)",
    }),
];

export const DEFAULT_THEME_NAME = "Warm Paper";
