export const THEME_TOKEN_MAP = {
    "background.primary": "--color-bg-primary",
    "background.secondary": "--color-bg-secondary",
    "background.tertiary": "--color-bg-tertiary",
    "text.primary": "--color-text-primary",
    "text.secondary": "--color-text-secondary",
    "text.tertiary": "--color-text-tertiary",
    "text.muted": "--color-text-muted",
    "text.link": "--color-text-link",
    "border.light": "--color-border-light",
    "border.medium": "--color-border-medium",
    "border.dark": "--color-border-dark",

    "neutral.50": "--color-gray-50",
    "neutral.100": "--color-gray-100",
    "neutral.200": "--color-gray-200",
    "neutral.300": "--color-gray-300",
    "neutral.400": "--color-gray-400",
    "neutral.500": "--color-gray-500",
    "neutral.600": "--color-gray-600",
    "neutral.700": "--color-gray-700",
    "neutral.800": "--color-gray-800",
    "neutral.900": "--color-gray-900",

    "accent.50": "--color-blue-50",
    "accent.100": "--color-blue-100",
    "accent.200": "--color-blue-200",
    "accent.300": "--color-blue-300",
    "accent.400": "--color-blue-400",
    "accent.500": "--color-blue-500",
    "accent.600": "--color-blue-600",
    "accent.700": "--color-blue-700",
    "accent.800": "--color-blue-800",
    "accent.900": "--color-blue-900",
    "accent.default": "--color-accent-default",
    "accent.swatch1": "--color-accent-swatch-1",
    "accent.swatch2": "--color-accent-swatch-2",
    "accent.swatch3": "--color-accent-swatch-3",
    "accent.swatch4": "--color-accent-swatch-4",
    "accent.swatch5": "--color-accent-swatch-5",
    "accent.swatch6": "--color-accent-swatch-6",

    "semantic.primary": "--primary",
    "semantic.primaryForeground": "--primary-foreground",
    "semantic.secondary": "--secondary",
    "semantic.secondaryForeground": "--secondary-foreground",
    "semantic.muted": "--muted",
    "semantic.mutedForeground": "--muted-foreground",
    "semantic.accent": "--accent",
    "semantic.accentForeground": "--accent-foreground",
    "semantic.destructive": "--destructive",
    "semantic.destructiveForeground": "--destructive-foreground",
    "semantic.border": "--border",
    "semantic.input": "--input",
    "semantic.ring": "--ring",

    "sidebar.background": "--sidebar",
    "sidebar.foreground": "--sidebar-foreground",
    "sidebar.primary": "--sidebar-primary",
    "sidebar.primaryForeground": "--sidebar-primary-foreground",
    "sidebar.accent": "--sidebar-accent",
    "sidebar.accentForeground": "--sidebar-accent-foreground",
    "sidebar.border": "--sidebar-border",
    "sidebar.ring": "--sidebar-ring",

    "graph.background": "--graph-bg",
    "graph.node": "--graph-node",
    "graph.nodeOrphan": "--graph-node-orphan",
    "graph.nodeMissing": "--graph-node-missing",
    "graph.nodeLabel": "--graph-node-label",
    "graph.edge": "--graph-edge",
    "graph.edgeBroken": "--graph-edge-broken",
    "graph.nodeActive": "--graph-node-active",

    "code.string": "--syntax-string",
    "code.function": "--syntax-function",
    "code.hashtag": "--cm-hashtag",
    "code.hashtagBg": "--cm-hashtag-bg",

    "panel.background": "--color-panel-bg",
    "panel.border": "--color-panel-border",
    "panel.header": "--color-panel-header",
    "panel.footer": "--color-panel-footer",
    "panel.hover": "--color-panel-hover",
    "panel.active": "--color-panel-active",
    "overlay.scrim": "--color-overlay-scrim",
    "highlight.background": "--color-highlight-bg",
    "highlight.text": "--color-highlight-text",
    "kbd.background": "--color-kbd-bg",
    "kbd.border": "--color-kbd-border",
    "kbd.text": "--color-kbd-text",
    "alert.background": "--color-alert-bg",
    "alert.border": "--color-alert-border",
    "alert.text": "--color-alert-text",
    "callout.default": "--callout-color",
    "callout.info": "--callout-info",
    "callout.tip": "--callout-tip",
    "callout.warning": "--callout-warning",
    "callout.danger": "--callout-danger",
    "callout.success": "--callout-success",
    "callout.example": "--callout-example",
    "callout.quote": "--callout-quote",
    "callout.terminal": "--callout-terminal",
} as const;

export type ThemeTokenKey = keyof typeof THEME_TOKEN_MAP;

export type ThemeTokenMap = Partial<Record<ThemeTokenKey, string>>;

export const THEME_TOKEN_KEYS = Object.keys(THEME_TOKEN_MAP) as ThemeTokenKey[];

export function getCssVarForToken(token: ThemeTokenKey): string {
    return THEME_TOKEN_MAP[token];
}
